modLoader="javafml"
loaderVersion="[28,)"
license="GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007"

[[mods]] #mandatory
    modId="aequivaleo"
    version="${version}"
    displayName="Aequivaleo"
    authors="OrionOnline, LDTTeam"
    description='''
        Mediator mod which allows for high performance analysis of recipes, their inputs and outputs.
    '''
    [[dependencies.mantle]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"
        side="BOTH"
