modLoader="javafml"
loaderVersion="[28,)"
license="GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007"

[[mods]] #mandatory
    modId="aequivaleo"
    version="0.1.17-ALPHA"#"${version}"
    displayName="Aequivaleo"
    authors="OrionOnline, LDTTeam"
    description='''
        Mediator mod which allows for high performance analysis of recipes, their inputs and outputs.
    '''
